### ISSUE TITLE
Add timing for each window.

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/mhealthtools#11]
For data where we are summarizing a single activitity the windows are treated as repeat measures but for other tasks we are interested in the change over time.  For example, for Heart rate we are interested in the change in HR and need to know the time for each window.  I suggest adding the start timestamp and end timestamp for each window.

**Comment by th1vairam** [comment]
@philerooski We need to output the start and end timestamp in get window signal function. Let me know if you need help.
