### ISSUE TITLE
Uniformity of tap_features vs tapFeatures in get_tap_features.R

### ISSUE THREAD

**Issue by itismeghasyam** [Sage-Bionetworks/mhealthtools#126]
https://github.com/Sage-Bionetworks/mhealthtools/blob/develop/R/get_tapping_features.R

- I don't know when this was changed, but this file has styles mixed up. tap_features(L38, L51, L53, L57) vs tapFeatures(L40, L42), and that is causing the function to break, along with it the associated tests.

@philerooski I see an issue open on Styling, will this be fixed in that?

I can't write tests as they fill wail, will wait for fixes to be done 😄

**Comment by philerooski** [comment]
Sure, I'll fix.
