### ISSUE TITLE
[Joss Review] Paper

### ISSUE THREAD

**Issue by AKuederle** [Sage-Bionetworks/mhealthtools#210]
Hey everybody,

I will collect my thoughts on the paper here (I will try not to repeat points form the other reviewers)

- Paper is well written and nicely explains the structure of the model

Issues:
- [x] You mention that various other libraries exist. I would like to see a comparison of these packages to your module to further strengthen your statement of need.

**Comment by philerooski** [comment]
This is in progress but will take a bit of time.

**Comment by philerooski** [comment]
Hi @AKuederle, I've added a section at the end which compares mhealthtools to similar packages in the digital health domain. If it's satisfactory to you we can close this issue.

**Comment by AKuederle** [comment]
Good from my side! Thank you for adding this!
