### ISSUE TITLE
kinematic_sensor_argument_validator limiting time filter to <50

### ISSUE THREAD

**Issue by JulioV** [Sage-Bionetworks/mhealthtools#215]
This line stops `time_filter` from being bigger than 50. This seems to be a bug as the user could have a time series longer than 50s https://github.com/Sage-Bionetworks/mhealthtools/blob/c4a0af57c594bc9cba11751a0836e6819499b576/R/sensors.R#L360

**Comment by philerooski** [comment]
Ohh that is definitely a bug. Easy fix, fortunately.

Keep in mind that these IMU feature extraction functions were originally designed to work with sensor data recordings of less than a minute. I've used this package to extract features over 20-minute recordings and it took a loooong time.

**Comment by philerooski** [comment]
Blocked by #217
