### ISSUE TITLE
recommend docs for all major functions to have self contained examples (even if with dummy data)

### ISSUE THREAD

**Issue by apratap** [Sage-Bionetworks/mhealthtools#43]
Goes a long way to get more people interested and adopt

**Comment by th1vairam** [comment]
@apratap Great suggestions. If you check out this markdown here https://github.com/Sage-Bionetworks/mhealthtools/blob/develop/vignettes/Introduction%20to%20mhealthtools.Rmd explains what vignettes are available or will be available in the near future. Do you suggest more than this for all the utility functions too?

**Comment by apratap** [comment]
My suggestion was that help on major functions should have demo code (hopefully self-contained)

?mhealthtools::get_tapping_features -> lacks any example

**Comment by th1vairam** [comment]
@itismeghasyam check @apratap suggestion. Basically, move some of the content in the vignettes to the main functions themselves using /examples tag. Check roxygen2 on how to write examples.

**Comment by philerooski** [comment]
Resolved by #88
