### ISSUE TITLE
Include a jerk column with transform_gyroscope_data

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/mhealthtools#49]
This makes the schemas of both transformed accelerometer data and transformed gyroscope data the same (for equivalent `transfromation`s), meaning we can pass the same models to both `accelerometer_features` and `gyroscope_features` (or a single model list to assay level modules that have a models parameter)

**Comment by th1vairam** [comment]
For brevity and non-usability of Jerk features in Gyroscope, we decided not to extract these features. So I am closing this issue.
