### ISSUE TITLE
have a way to run multiple JSON tapping/walking/gait files with error catching

### ISSUE THREAD

**Issue by apratap** [Sage-Bionetworks/mhealthtools#60]
Right now the functions are written to extract features for a single file which is how it should be. It will be helpful if we write looping functions that are able to capture errors when multiple JSON files are run.

See example here - https://github.com/Sage-Bionetworks/mpowertools/blob/master/R/tappingModule.R#L201

**Comment by philerooski** [comment]
How it's currently handled is that any errors will be returned as an "error tibble" which is just a dataframe with an `error` column. So when someone inevitably writes a wrapper around mhealthtools to perform batch processing (like what we have in `Sage-Bionetworks/mPowerAnalysis/featureExtraction`) it will be up to them to implement their wrapper in such a way as to attach some index values (like `recordId`, for example) to the returned result so they can identify which records had errors in the feature extraction process.

In the case of our mPowerAnalysis wrappers, we append this error tibble -- with identifying information -- to the extracted features from all the other records. During analysis, it's easy to filter out the records that threw errors.

Is this what you had in mind?

**Comment by th1vairam** [comment]
@apratap As per our last mHealth standup discussions, it has been decided that Sage specific wrappers are needed to use mhealthtools. However, that will be in a separate repository in parallel to mhealthools. 

@philerooski can you create a new repository with an appropriate name and move/reference this issue there and close it here. Thank you.
