### ISSUE TITLE
Redundant tapping features functionality

### ISSUE THREAD

**Issue by th1vairam** [Sage-Bionetworks/mhealthtools#61]
Why there are two functions with very similar use cases? get_tapping_features and tapping_features? Do we really need them both?

**Comment by itismeghasyam** [comment]
I just named them that ways, so that if need arises, we can incorporate models into tapping like we did for accelerometer and gyroscope. If not, then we can possibly get rid of one of those

**Comment by th1vairam** [comment]
I would remove the tapping_features.R and move all of its content to get_tapping_features.R. If needed we can add this later. For now, we keep this repo slim and less-redundant.
