### ISSUE TITLE
Fix models argument in tests

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/mhealthtools#64]
There are a few tests where the incorrect object type is passed to the `models` parameter. `models` should be a list of named models (like `models = list(my_custom_model = custom_model)`) rather than a single function (`models = custom_model`).

I see this error in
* `test_get_walk_features`
* `test_get_tremor_features`
* `test_get_rest_features`
* `test_get_kinetic_tremor_features`

**Comment by itismeghasyam** [comment]
This is related to #65  and #66 , and would be best if changed along with them together

**Comment by philerooski** [comment]
Similar in the sense they are small, easy fixes, sure. But otherwise they are completely independent issues. I can reassign myself to this issue if you like.

**Comment by itismeghasyam** [comment]
I think that would be the best
