### ISSUE TITLE
Possible reference missed ?

### ISSUE THREAD

**Issue by itismeghasyam** [Sage-Bionetworks/mhealthtools#76]
```
restFeatures <- mhealthtools::get_rest_features(
+         accelerometer_data = restData$accelerometer,
+         gyroscope_data = restData$gyroscope,
+         gravity_data = restData$gravity,
+         funs = mhealthtools:::default_kinematic_features(samplingRate)
+     )
```
I got the following error when I tried to do the above for the first time on my Windows PC

```
Error in mutate_impl(.data, dots) : 
  Evaluation error: there is no package called <U+0091>fractal<U+0092>.
```

**Comment by philerooski** [comment]
Can you include a reproducible example? I ran this using the sample data included with the package with a fresh install from the develop branch and had no issues.

**Comment by philerooski** [comment]
Try this after reinstalling from develop:

```
restFeatures <- mhealthtools::get_rest_features(
              accelerometer_data = mhealthtools::accelerometer_data,
              gyroscope_data = mhealthtools::gyroscope_data,
              gravity_data = mhealthtools::gravity_data,
              funs = mhealthtools:::default_kinematic_features(100))
```

**Comment by itismeghasyam** [comment]
Did you try it in windows?
I don't know how else to put a reproducible example out there other than paste the code that caused me the error.....

**Comment by philerooski** [comment]
`restData$accelerometer` What is restData?
`funs = mhealthtools:::default_kinematic_features(samplingRate)` What is samplingRate?

It's not that important in this case because those inputs probably aren't causing the error you're seeing, but it's always good to include code that others can run (otherwise we can't help!).

Copy and paste this code block (after restarting your R session) and tell me if you still get the error:

```
devtools::install_github("Sage-Bionetworks/mhealthtools@develop")
mhealthtools::get_rest_features(
              accelerometer_data = mhealthtools::accelerometer_data,
              gyroscope_data = mhealthtools::gyroscope_data,
              gravity_data = mhealthtools::gravity_data,
              funs = mhealthtools:::default_kinematic_features(100))
```

**Comment by itismeghasyam** [comment]
Gotcha! Will do again tonight 👍

**Comment by philerooski** [comment]
Turns out we are calling a function from the fractal package, but it isn't explicitly referenced (like `fractal::func()`), so it never got automatically added to `DESCRIPTION`. The function is somewhere in the included feature extraction functions in `utils.R`.

**Comment by th1vairam** [comment]
@itismeghasyam can you find the fractal function and explicitly reference it? open a new pull based on that.

**Comment by itismeghasyam** [comment]
I found the function, we are using fractal for detrented fluctuation analysis (dfa).

We are referencing the function using fractal::dfa. We just missed specifying fractal as a required package.

https://github.com/Sage-Bionetworks/mhealthtools/blob/master/R/utils.R#660

**Comment by philerooski** [comment]
Huh. I thought devtools would be smart enough to add the package to Imports if we reference it. Guess not.
