### ISSUE TITLE
Incorporate transformation parameter into assay level modules

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/mhealthtools#91]
From #86 

As it's currently implemented, the transformation function is strictly defined for each assay level feature extraction function. In fact, this is the only thing that differentiates one assay function from another.

This change will allow the user to specify the `transformation` used at the assay level. If a user passes `NULL`, we apply preprocessing (if preprocessing parameters are passed) but don't apply a transformation to the preprocessed data. If a user doesn't pass an argument to `transformation`, we will apply the current default transformation. So if a user omits `transformation` from `get_tremor_features`, we will implicitly apply 

```
transformation = transformation_window(
  window_length = 256, # the default parameters
  overlap = 0.5)
```

One downside to this approach is that the user may be unaware they are using `window_length = 256` and `overlap = 0.5` in the `transformation`, and set different values for `window_length` and `overlap` in the preprocessing steps. @th1vairam can you comment on how serious of an issue this is?

I suggest we allow users to pass either a function or vector of functions to the `transformation` parameter. A vector of functions would mean that each transformation is applied sequentially to preprocessed data. This functionality would need to be extended to the sensor level feature extraction functions as well.

**Comment by th1vairam** [comment]
Refer #93 for comments. 

Again the I am not super clear on your definitions of `transformation` and `preprocess`. Some clarity would help here. if my comments don't make any sense then find me F2F to discuss.
